/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ahp_gui1.MyPanels;

import ahp_gui1.AHP;
import ahp_gui1.AHPCanvas;
import ahp_gui1.Kryterium;
import java.awt.*;
import javax.swing.DefaultListModel;

/**
 *
 * @author Un1kalny
 */
public class Panel2 extends javax.swing.JPanel {
    AHP ahp;
    DefaultListModel listModel1 = new DefaultListModel();
    DefaultListModel listModel2 = new DefaultListModel();
    String taby = "";
    /**
     * Creates new form Panel2
     */
    public Panel2(AHP ahp) {
        this.ahp = ahp;
        initComponents();
    }
    
    void rekurencyjnePrzechodzenieKryteriow(Kryterium kr) {
        if(kr.listaPodkryteriow != null) {
            taby += "       ";
            for(int i = 0; i < kr.listaPodkryteriow.size(); ++i) {
                String nazwaZTabami = taby + kr.listaPodkryteriow.get(i);
                listModel2.addElement(nazwaZTabami);
                rekurencyjnePrzechodzenieKryteriow(kr.listaPodkryteriow.get(i));
            }
            if(taby.length() >= 8)
                    taby = taby.substring(0, taby.length() - 8);
        }
    }
    
    void update() {
        for(int i = 0; i < ahp.cele.size(); ++i) {
            listModel1.addElement(ahp.cele.get(i));
        }
        for(int i = 0; i < ahp.kryteria.size(); ++i) {
            if(ahp.kryteria.get(i).parent == null) {
                listModel2.addElement(ahp.kryteria.get(i).nazwa);
                rekurencyjnePrzechodzenieKryteriow(ahp.kryteria.get(i));
                taby = "";
            }
        }
    }
    
    public void clearPanel() {
        listModel1.clear();
        listModel2.clear();
    }

    /*public void ustawTextLabela(String text) {
        jLabel1.setText(text);
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

        setPreferredSize(new java.awt.Dimension(878, 567));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Goals:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Criterias and subcriterias:");

        jList1.setModel(listModel1);
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(listModel2);
        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
